
name: build

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build cesium-native
        run: ./build-all.sh release

      - name: Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: libcesium.a.zip
          path: |
            build/release/pkg/libcesium.a.xcframework.zip
            build/release/pkg/libcesium.a.xcframework.zip.sha256.txt
